/**
 * 艦長スキル翻訳用composable
 * 内部スキル名（CamelCase）から日本語/英語表示名への変換
 */

// 内部名 → 日本語名
const SKILLS_JA: Record<string, string> = {
  GmReloadAaDamageConstant: '装填手',
  DefenceCritFireFlooding: '応急対応の基本',
  GmTurn: '歯車のグリスアップ',
  TorpedoReload: '魚雷装填手',
  ConsumablesCrashcrewRegencrewReload: '緊急修理技術者',
  ConsumablesDuration: '消耗品強化',
  DetectionTorpedoRange: '警戒',
  HeFireProbability: '爆発物専門家',
  GmRangeAaDamageBubbles: '主砲・対空兵装専門家',
  PlanesDefenseDamageConstant: '航空機装甲',
  PlanesForsageDuration: 'エンジンブースト改良',
  DetectionVisibilityRange: '隠蔽処理専門家',
  ConsumablesReload: '消耗品技術者',
  DefenceFireProbability: '防火処理専門家',
  PlanesAimingBoost: '照準安定化',
  PlanesSpeed: 'エンジン改良',
  ConsumablesAdditional: '管理',
  DefenseCritProbability: '予防整備',
  DetectionAlert: '危険察知',
  Maneuverability: '最後の抵抗',
  GmShellReload: '装填手',
  PlanesConsumablesCallfightersUpgrade: '索敵掃討',
  ArmamentReloadAaDamage: 'アドレナリン・ラッシュ',
  TorpedoSpeed: '高速魚雷',
  DefenseHp: '抗堪専門家',
  AtbaAccuracy: '副砲の手動照準',
  AaPrioritysectorDamageConstant: '集中砲火訓練',
  DetectionAiming: '敵弾接近警報',
  PlanesReload: '制空権',
  TorpedoDamage: '強烈な打撃力',
  ConsumablesFighterAdditional: '戦闘機指揮所',
  PlanesConsumablesSpeedboosterReload: 'エンジン技師',
  HePenetration: '榴弾用慣性信管',
  DetectionDirection: '無線方向探知',
  AaDamageConstantBubbles: '対空・対潜専門家',
  AaDamageConstantBubblesCv: '副砲専門家',
  ApDamageBb: '超重徹甲弾',
  ApDamageCa: '重徹甲弾',
  ApDamageDd: '特重弾薬',
  AtbaRange: '長射程副砲弾',
  AtbaUpgrade: '副砲照準改良',
  ConsumablesCrashcrewRegencrewUpgrade: '改良型修理班準備',
  ConsumablesSpotterUpgrade: '上空の眼',
  DefenceUw: '緊急修理専門家',
  DetectionVisibilityCrashcrew: '隠れた脅威',
  HeFireProbabilityCv: '爆発物専門家',
  HeSapDamage: '重榴弾・SAP弾',
  PlanesApDamage: '強化型徹甲弾',
  PlanesConsumablesCallfightersAdditional: '偵察隊リーダー',
  PlanesConsumablesCallfightersPreparationtime: '強化型反応速度',
  PlanesConsumablesCallfightersRange: '迎撃機',
  PlanesConsumablesRegeneratehealthUpgrade: '修理技術者',
  PlanesDefenseDamageBubbles: '強化型航空機装甲',
  PlanesDivebomberSpeed: '爆撃機の飛行制御',
  PlanesForsageRenewal: '最後の奮闘',
  PlanesHp: '抗堪専門家',
  PlanesTorpedoArmingrange: '雷撃機',
  PlanesTorpedoSpeed: '高速航空魚雷',
  PlanesTorpedoUwReduced: '近接信管',
  TorpedoFloodingProbability: '水浸し',
  TriggerSpeedBb: '活発',
  TriggerGmAtbaReloadBb: '接近戦',
  TriggerGmAtbaReloadCa: '最上級砲手',
  TriggerGmReload: '恐れ知らずの喧嘩屋',
  TriggerSpeed: '素早く静かに',
  TriggerSpeedAccuracy: '数的劣勢',
  TriggerSpreading: '幻惑',
  TriggerPingerReloadBuff: '強化型ソナー',
  TriggerPingerSpeedBuff: '強化型インパルス発生器',
  SubmarineHoldSectors: 'ソナー操作員',
  TriggerSeenTorpedoReload: '魚雷員訓練',
  SubmarineTorpedoPingDamage: '魚雷誘導マスター',
  TriggerConsRudderTimeCoeff: '操舵手',
  SubmarineBatteryCapacity: '改良型バッテリー容量',
  SubmarineDangerAlert: '敵弾接近警報',
  SubmarineBatteryBurnDown: '改良型バッテリー効率',
  SubmarineSpeed: '大型プロペラ・シャフト',
  SubmarineConsumablesReload: '消耗品技術者',
  SubmarineConsumablesDuration: '消耗品強化',
  TriggerBurnGmReload: '猛烈',
  ArmamentReloadSubmarine: 'アドレナリン・ラッシュ',
}

// 内部名 → 英語名
const SKILLS_EN: Record<string, string> = {
  GmReloadAaDamageConstant: 'Gun Feeder',
  DefenceCritFireFlooding: 'Basics of Survivability',
  GmTurn: 'Grease the Gears',
  TorpedoReload: 'Fill the Tubes',
  ConsumablesCrashcrewRegencrewReload: 'Emergency Repair Specialist',
  ConsumablesDuration: 'Consumable Enhancements',
  DetectionTorpedoRange: 'Vigilance',
  HeFireProbability: 'Demolition Expert',
  GmRangeAaDamageBubbles: 'Main Battery and AA Specialist',
  PlanesDefenseDamageConstant: 'Aircraft Armor',
  PlanesForsageDuration: 'Improved Engine Boost',
  DetectionVisibilityRange: 'Concealment Expert',
  ConsumablesReload: 'Consumable Specialist',
  DefenceFireProbability: 'Fire Prevention Expert',
  PlanesAimingBoost: 'Aiming Facility Maintenance',
  PlanesSpeed: 'Improved Engines',
  ConsumablesAdditional: 'Superintendent',
  DefenseCritProbability: 'Preventive Maintenance',
  DetectionAlert: 'Priority Target',
  Maneuverability: 'Last Stand',
  GmShellReload: 'Expert Loader',
  PlanesConsumablesCallfightersUpgrade: 'Search and Destroy',
  ArmamentReloadAaDamage: 'Adrenaline Rush',
  TorpedoSpeed: 'Swift Fish',
  DefenseHp: 'Survivability Expert',
  AtbaAccuracy: 'Manual Secondary Battery Aiming',
  AaPrioritysectorDamageConstant: 'Focus Fire Training',
  DetectionAiming: 'Incoming Fire Alert',
  PlanesReload: 'Air Supremacy',
  TorpedoDamage: 'Pack A Punch',
  ConsumablesFighterAdditional: 'Direction Center for Fighters',
  PlanesConsumablesSpeedboosterReload: 'Engine Techie',
  HePenetration: 'Inertia Fuse for HE Shells',
  DetectionDirection: 'Radio Location',
  AaDamageConstantBubbles: 'AA Defense and ASW Expert',
  AaDamageConstantBubblesCv: 'Secondary Armament Expert',
  ApDamageBb: 'Super-Heavy AP Shells',
  ApDamageCa: 'Heavy AP Shells',
  ApDamageDd: 'Extra-Heavy Ammunition',
  AtbaRange: 'Long-Range Secondary Battery Shells',
  AtbaUpgrade: 'Improved Secondary Battery Aiming',
  ConsumablesCrashcrewRegencrewUpgrade: 'Improved Repair Party Readiness',
  ConsumablesSpotterUpgrade: 'Eye in the Sky',
  DefenceUw: 'Emergency Repair Expert',
  DetectionVisibilityCrashcrew: 'Hidden Menace',
  HeFireProbabilityCv: 'Pyrotechnician',
  HeSapDamage: 'Heavy HE and SAP Shells',
  PlanesApDamage: 'Enhanced Armor-Piercing Ammunition',
  PlanesConsumablesCallfightersAdditional: 'Patrol Group Leader',
  PlanesConsumablesCallfightersPreparationtime: 'Enhanced Reactions',
  PlanesConsumablesCallfightersRange: 'Interceptor',
  PlanesConsumablesRegeneratehealthUpgrade: 'Repair Specialist',
  PlanesDefenseDamageBubbles: 'Enhanced Aircraft Armor',
  PlanesDivebomberSpeed: 'Bomber Flight Control',
  PlanesForsageRenewal: 'Last Gasp',
  PlanesHp: 'Survivability Expert',
  PlanesTorpedoArmingrange: 'Torpedo Bomber',
  PlanesTorpedoSpeed: 'Torpedo Bomber Acceleration',
  PlanesTorpedoUwReduced: 'Proximity Fuze',
  TorpedoFloodingProbability: 'Liquidator',
  TriggerSpeedBb: 'Brisk',
  TriggerGmAtbaReloadBb: 'Close Quarters Expert',
  TriggerGmAtbaReloadCa: 'Top Grade Gunner',
  TriggerGmReload: 'Fearless Brawler',
  TriggerSpeed: 'Swift in Silence',
  TriggerSpeedAccuracy: 'Outnumbered',
  TriggerSpreading: 'Dazzle',
  TriggerPingerReloadBuff: 'Enhanced Sonar',
  TriggerPingerSpeedBuff: 'Enhanced Impulse Generator',
  SubmarineHoldSectors: 'Sonar Operator',
  TriggerSeenTorpedoReload: 'Torpedo Crew Training',
  SubmarineTorpedoPingDamage: 'Homing Torpedo Expert',
  TriggerConsRudderTimeCoeff: 'Helmsman',
  SubmarineBatteryCapacity: 'Improved Battery Capacity',
  SubmarineDangerAlert: 'Incoming Fire Alert',
  SubmarineBatteryBurnDown: 'Improved Battery Efficiency',
  SubmarineSpeed: 'Enlarged Propeller Shaft',
  SubmarineConsumablesReload: 'Improved Consumables',
  SubmarineConsumablesDuration: 'Extended Consumables',
  TriggerBurnGmReload: 'Furious',
  ArmamentReloadSubmarine: 'Submarine Adrenaline Rush',
}

export const useCaptainSkills = () => {
  /**
   * 内部スキル名から表示名を取得
   */
  const getSkillName = (internalName: string, locale: string = 'ja'): string => {
    const dict = locale === 'ja' ? SKILLS_JA : SKILLS_EN
    return dict[internalName] || internalName
  }

  /**
   * スキル名配列を一括変換
   */
  const translateSkills = (skills: string[], locale: string = 'ja'): string[] => {
    return skills.map(s => getSkillName(s, locale))
  }

  return {
    getSkillName,
    translateSkills,
  }
}
